DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE endpoints (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT UNIQUE NOT NULL,
  access TEXT NOT NULL,
  status TEXT NOT NULL,
  endpoint_base TEXT UNIQUE NOT NULL,
  tags TEXT,
  data TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);